/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideoRouteImport } from './routes/video'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as ModpackRouteImport } from './routes/modpack'
import { Route as MapRouteImport } from './routes/map'
import { Route as EventsRouteImport } from './routes/events'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StatsS0RouteImport } from './routes/stats.s0'

const VideoRoute = VideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const ModpackRoute = ModpackRouteImport.update({
  id: '/modpack',
  path: '/modpack',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsS0Route = StatsS0RouteImport.update({
  id: '/s0',
  path: '/s0',
  getParentRoute: () => StatsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/map': typeof MapRoute
  '/modpack': typeof ModpackRoute
  '/rules': typeof RulesRoute
  '/stats': typeof StatsRouteWithChildren
  '/video': typeof VideoRoute
  '/stats/s0': typeof StatsS0Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/map': typeof MapRoute
  '/modpack': typeof ModpackRoute
  '/rules': typeof RulesRoute
  '/stats': typeof StatsRouteWithChildren
  '/video': typeof VideoRoute
  '/stats/s0': typeof StatsS0Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/map': typeof MapRoute
  '/modpack': typeof ModpackRoute
  '/rules': typeof RulesRoute
  '/stats': typeof StatsRouteWithChildren
  '/video': typeof VideoRoute
  '/stats/s0': typeof StatsS0Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/events'
    | '/map'
    | '/modpack'
    | '/rules'
    | '/stats'
    | '/video'
    | '/stats/s0'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/events'
    | '/map'
    | '/modpack'
    | '/rules'
    | '/stats'
    | '/video'
    | '/stats/s0'
  id:
    | '__root__'
    | '/'
    | '/events'
    | '/map'
    | '/modpack'
    | '/rules'
    | '/stats'
    | '/video'
    | '/stats/s0'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventsRoute: typeof EventsRoute
  MapRoute: typeof MapRoute
  ModpackRoute: typeof ModpackRoute
  RulesRoute: typeof RulesRoute
  StatsRoute: typeof StatsRouteWithChildren
  VideoRoute: typeof VideoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/video': {
      id: '/video'
      path: '/video'
      fullPath: '/video'
      preLoaderRoute: typeof VideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modpack': {
      id: '/modpack'
      path: '/modpack'
      fullPath: '/modpack'
      preLoaderRoute: typeof ModpackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/s0': {
      id: '/stats/s0'
      path: '/s0'
      fullPath: '/stats/s0'
      preLoaderRoute: typeof StatsS0RouteImport
      parentRoute: typeof StatsRoute
    }
  }
}

interface StatsRouteChildren {
  StatsS0Route: typeof StatsS0Route
}

const StatsRouteChildren: StatsRouteChildren = {
  StatsS0Route: StatsS0Route,
}

const StatsRouteWithChildren = StatsRoute._addFileChildren(StatsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventsRoute: EventsRoute,
  MapRoute: MapRoute,
  ModpackRoute: ModpackRoute,
  RulesRoute: RulesRoute,
  StatsRoute: StatsRouteWithChildren,
  VideoRoute: VideoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
